export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as AllPuppies} from './AllPuppies'
export {default as Searchbar} from './Searchbar'
export {default as SinglePuppy} from './SinglePuppy'
export {default as PuppyDaTails} from './PuppyDaTails'